# Generated by Django 2.2.13 on 2020-07-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='events',
            field=models.IntegerField(default=1, verbose_name='Events'),
            preserve_default=False,
        ),
    ]
